packages:
  - packages/*

catalogs:
  dev:
    '@antfu/eslint-config': ^4.2.1
    '@antfu/ni': ^23.3.1
    '@types/node': ^22.13.4
    bumpp: ^10.0.3
    eslint: ^9.20.1
    h3: npm:h3-nightly@2x
    lint-staged: ^15.4.3
    simple-git-hooks: ^2.11.1
    tsdown: ^0.9.9
    tsx: ^4.19.2
    typescript: ^5.7.3
    vitest: ^3.0.5
    pnpm: ^10.4.0

  client:
    nuxt: ^3.16.2
    vue: ^3.5.13
    vue-router: ^4.5.0

  dependencies:
    h3: npm:h3-nightly@2x
    pathe: ^2.0.3
